Update UI. Fix #11
vietabroader/VAQR pull request #14
Opened 2017-06-22 02:43 UTC by ellienguyen

2017-06-22 07:04 UTC, ctring commented
I think you misunderstood my drawing.

- The notification label should be between the Spreadsheet and Workspace sections. We'll use this to tell the user what's going on.
- The refresh button should be to the right of Key Columns section. It should have a square shape; do this by using `setPreferredSize` as I did with the `webcamButton`
- The webcam label is not below the Start Webcam button. Try clicking on the Start Webcam button, you'll see a new window appear with the webcam. Put the label right below the area that shows the picture.

2017-06-22 15:59 UTC, ellienguyen commented
For some reason, I cannot close the webcam panel by clicking the close icon or Ctrl+C in Terminal and have to Force Quit to exit. Could you help me with that?

2017-06-22 16:10 UTC, ellienguyen commented
![image](https://user-images.githubusercontent.com/18899970/27444205-3e757eac-573b-11e7-8e4f-88ef13988956.png)
![image](https://user-images.githubusercontent.com/18899970/27444264-680d691e-573b-11e7-851b-156bb431c671.png)
Here is the screenshot. Is this what you meant?

2017-06-23 04:12 UTC, ctring requested changes
Yes. This looks good.

2017-06-23 04:12 UTC, ctring commented on src/main/java/org/vietabroader/view/MainView.java
> +        JButton btnRefresh = new JButton("Refresh");
Wrap the refresh button and the column panel into one panel. This way we can control their size without affecting other components

2017-06-23 14:57 UTC, ellienguyen commented
It seems I have done something wrong with Git again :)) I pull --rebase from upstream master, update my branch then fail to push to my origin:feature_branch. I try to rebase from my feature_branch and it let me push things up to origin. But then Git doesn't let me rebase and merge (but only squash and merge). Could you give me an advice? Thanks. @ctring

2017-06-24 06:26 UTC, ctring commented
![screen shot 2017-06-23 at 11 14 48 pm](https://user-images.githubusercontent.com/6244849/27506303-4c9bdae6-586a-11e7-9317-3b330f4f8dbb.png)

If you do pull --rebase then rebase correctly, the branch, update-ui here for example, would connect to the master branch indicated by the blue mark, without the 2 duplicated commit on top. 

I can imagine that you only do pull --rebase while on the update-ui branch. Going back to the [document](https://docs.google.com/document/d/1SQi2pmV8l63cQDL1k9dxWgrCZ4qc2jvV8_fJJ2Q8tUQ/edit), in section **Fetch + Rebase local master**, I listed 2 steps:
- First you go back to the master branch and call pull --rebase there to update the master branch.
- Then you go back to your feature branch and rebase it onto the new master branch.

2017-06-24 06:33 UTC, ctring commented
<img width="749" alt="screen shot 2017-06-23 at 11 32 06 pm" src="https://user-images.githubusercontent.com/6244849/27506449-3db542ae-586c-11e7-9275-667664b76aa2.png">

Your current repo should look similar to this.

In case you wonder how to get the log view like that, run:
`git log --graph --decorate --oneline --all`

2017-06-24 06:49 UTC, ctring requested changes

2017-06-24 06:49 UTC, ctring commented on src/main/java/org/vietabroader/view/verifier/SheetVerifier.java
> +public class SheetVerifier extends InputVerifier {
This is a good idea. Use another name since `SheetVerifier` is kinda misleading. Maybe `TextFieldVerifier`, or just `TextVerifier` ?

2017-06-24 06:49 UTC, ctring commented on src/main/java/org/vietabroader/view/verifier/SheetVerifier.java
> +    public boolean verify(JComponent input) {
The goal of this class seems to only be unifying the `shouldYieldFocus` method. Remove this method override if it does not serve any purpose, and make this class abstract.

2017-06-24 06:53 UTC, ctring approved these changes
Oh wait, it seems that you already merge the SheetVerifier into master. Ignore my comments. I'll fix that for you. All you need to do for this pull request is rebase it correctly with the 2 steps. I'll merge it for you when I see it is in good shape.

2017-06-25 17:45 UTC, merged