Webcam
vietabroader/VAQR pull request #8
Opened 2017-06-17 21:49 UTC by nctl144

+ Add webcam panel to the Webcam Panel
+ Open the webcam in the new window, turn off the webcam when the window is closed

2017-06-18 20:34 UTC, ctring requested changes
Very good job!

2017-06-18 20:34 UTC, ctring commented on src/main/java/org/vietabroader/view/MainView.java
> +    public class MyAction implements ActionListener {
Rename to something more descriptive. OpenWebcamPanelAction for example

2017-06-18 20:34 UTC, ctring commented on src/main/java/org/vietabroader/view/MainView.java
> +            JFrame frame2 = new JFrame("QR code");
Renameto webcamFrame

2017-06-19 03:44 UTC, nctl144 commented
I have changed the names for classes and var as requested :)

2017-06-19 05:01 UTC, merged

2017-06-19 05:08 UTC, ctring commented
![branch](https://user-images.githubusercontent.com/6244849/27270279-e13bd1f8-5471-11e7-944a-5e1fd2400a58.png)

I'm not sure what happened but your branch look really weird. First is that the commits are duplicated and second is that you have 2 branches merge into one. If we follow our workflow correctly, which only involves rebasing, our branch will always have one line. If you have two branch merging into one then you're not rebasing. In the end, the code base is still the same but the history when doing rebase only is much cleaner.

2017-06-19 06:25 UTC, nctl144 commented
yes I see that. The problem is that I ran rebase after I committed some changes to the branch. I will pay attention to that closer next time :)